In [1]:
import pandas as pd

In [2]:
data = {
    "State":["Karnataka","Maharashtra","Tamil Nadu","Kerala","Delhi",
              "Gujarat","Rajasthan","Punjab","Uttar Pradesh","West Bengal"],

    "Population":[67500000,124000000,78000000,35600000,33000000,
                  71000000,81000000,31000000,240000000,100000000],

    "Literacy":[75.4,82.3,80.1,94.0,88.7,
                79.3,67.1,76.7,69.7,77.1],

    "Area":[191791,307713,130058,38863,1484,
            196024,342239,50362,243286,88752]
}

df = pd.DataFrame(data)

df

           State  Population  Literacy    Area
0      Karnataka    67500000      75.4  191791
1    Maharashtra   124000000      82.3  307713
2     Tamil Nadu    78000000      80.1  130058
3         Kerala    35600000      94.0   38863
4          Delhi    33000000      88.7    1484
5        Gujarat    71000000      79.3  196024
6      Rajasthan    81000000      67.1  342239
7         Punjab    31000000      76.7   50362
8  Uttar Pradesh   240000000      69.7  243286
9    West Bengal   100000000      77.1   88752

In [4]:
df.to_csv("Indian_States.csv", index=False)

In [6]:
df=pd.read_csv("Indian_States.csv")

In [7]:
print(df.shape)

(10, 4)

In [8]:
print(df.dtypes)

State          object
Population      int64
Literacy      float64
Area            int64
dtype: object

In [9]:
df.head(10)

           State  Population  Literacy    Area
0      Karnataka    67500000      75.4  191791
1    Maharashtra   124000000      82.3  307713
2     Tamil Nadu    78000000      80.1  130058
3         Kerala    35600000      94.0   38863
4          Delhi    33000000      88.7    1484
5        Gujarat    71000000      79.3  196024
6      Rajasthan    81000000      67.1  342239
7         Punjab    31000000      76.7   50362
8  Uttar Pradesh   240000000      69.7  243286
9    West Bengal   100000000      77.1   88752

In [10]:
# Filter states having population greater than 80 million

filtered=df[df["Population"]>80000000]

filtered

           State  Population  Literacy    Area
1    Maharashtra   124000000      82.3  307713
6      Rajasthan    81000000      67.1  342239
8  Uttar Pradesh   240000000      69.7  243286
9    West Bengal   100000000      77.1   88752

In [11]:
df["Region"]=["South","West","South","South","North",
              "West","North","North","North","East"]

df

           State  Population  Literacy    Area Region
0      Karnataka    67500000      75.4  191791  South
1    Maharashtra   124000000      82.3  307713   West
2     Tamil Nadu    78000000      80.1  130058  South
3         Kerala    35600000      94.0   38863  South
4          Delhi    33000000      88.7    1484  North
5        Gujarat    71000000      79.3  196024   West
6      Rajasthan    81000000      67.1  342239  North
7         Punjab    31000000      76.7   50362  North
8  Uttar Pradesh   240000000      69.7  243286  North
9    West Bengal   100000000      77.1   88752   East

In [12]:
# Average literacy by region

group=df.groupby("Region")["Literacy"].mean()

group

Region
East     77.100000
North    75.550000
South    83.166667
West     80.800000
Name: Literacy, dtype: float64

In [15]:
capital={
    "State":["Karnataka","Maharashtra","Tamil Nadu","Kerala",
             "Delhi","Gujarat","Rajasthan","Punjab",
             "Uttar Pradesh","West Bengal"],

    "Capital":["Bengaluru","Mumbai","Chennai","Thiruvananthapuram",
               "New Delhi","Gandhinagar","Jaipur","Chandigarh",
               "Lucknow","Kolkata"]
}

capital_df=pd.DataFrame(capital)

In [17]:
merged=pd.merge(df,capital_df,on="State")
merged

           State  Population  Literacy    Area Region             Capital
0      Karnataka    67500000      75.4  191791  South           Bengaluru
1    Maharashtra   124000000      82.3  307713   West              Mumbai
2     Tamil Nadu    78000000      80.1  130058  South             Chennai
3         Kerala    35600000      94.0   38863  South  Thiruvananthapuram
4          Delhi    33000000      88.7    1484  North           New Delhi
5        Gujarat    71000000      79.3  196024   West         Gandhinagar
6      Rajasthan    81000000      67.1  342239  North              Jaipur
7         Punjab    31000000      76.7   50362  North          Chandigarh
8  Uttar Pradesh   240000000      69.7  243286  North             Lucknow
9    West Bengal   100000000      77.1   88752   East             Kolkata

In [18]:
pivot=df.pivot_table(values="Population",
                     index="Region",
                     aggfunc="mean")
pivot

          Population
Region
East    1.000000e+08
North   9.625000e+07
South   6.036667e+07
West    9.750000e+07

In [19]:
merged.to_csv("Cleaned_Indian_States.csv", index=False)

In [20]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [34]:
merged.to_parquet("Cleaned_Indian_States.parquet", index=False)

In [35]:
import os

print(os.listdir())

['.config', 'Cleaned_Indian_States.csv', 'Cleaned_Indian_States.parquet', 'Indian_States.csv', 'sample_data']

In [36]:
import os

csv_size = os.path.getsize("Cleaned_Indian_States.csv")
parquet_size = os.path.getsize("Cleaned_Indian_States.parquet")

print("CSV Size:", csv_size, "bytes")
print("Parquet Size:", parquet_size, "bytes")

CSV Size: 508 bytes
Parquet Size: 4242 bytes

In [38]:
import os

In [39]:
csv_size=os.path.getsize("Cleaned_Indian_States.csv")

In [41]:
parquet_size=os.path.getsize("Cleaned_Indian_States.parquet")

In [42]:
print("CSV Size:", csv_size, "bytes")
print("Parquet Size:", parquet_size, "bytes")

CSV Size: 508 bytes
Parquet Size: 4242 bytes